version: "3.7"

networks:
  ben:
    driver: bridge

services:
  app:
    build: .
    user: root
    # command: python api.py
    # command: python create_alerts_database.py
    command: python -m hypercorn --bind 0.0.0.0:5001 --workers 4 starlette_api:app
    ports:
      - 5001:5001
    volumes:
      - ./src:/app/src
      - ./build/alerts_db:/var/lib/alerts_db
      - ./build/alerts_prep:/var/lib/alerts_prep
    environment:
      - ALERTS_DB_FILE=/var/lib/alerts_db/alert_database_1.sqlite
      - ALERTS_PREP_FILE=/var/lib/alerts_prep/alerts.pickle
      - TF_CPP_MIN_LOG_LEVEL=3
      - PORT=5001
      - DEBUG=true
      - USE_RELOADER=true
      - SENTRY_ENVIRONMENT=local
      - ENVIRONMENT=local
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=True
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=otel:4317
      - OTEL_SERVICE_NAME=robot
      - PROMETHEUS_MULTIPROC_DIR=/tmp/metrics
    networks:
      - ben

  otel:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "4317"
      - "16686:16686"
    networks:
      - ben
