version: "3.7"

networks:
  ben:
    driver: bridge

services:
  app:
    platform: linux/x86_64
    build: .
    user: root
    command: "api.py"
    ports:
      - 8081:8081
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_ENV=development
      - TF_CPP_MIN_LOG_LEVEL=3
      - DEBUG=true
    networks:
      - ben
