version: "3.7"

networks:
  ben:
    driver: bridge

services:
  app:
    build: .
    user: root
    # command: python api.py
    command: python create_alerts_database.py
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    environment:
      - TF_CPP_MIN_LOG_LEVEL=3
      - PORT=5001
      - DEBUG=true
      - USE_RELOADER=true
    networks:
      - ben
