version: "3.7"

networks:
  ben:
    driver: bridge

services:
  app:
    platform: linux/x86_64
    build: .
    command: "gameserver.py"
    ports:
      - 4443:4443
    networks:
      - ben

  web:
    platform: linux/x86_64
    build: .
    command: "webserver.py"
    ports:
      - 8080:8080
    networks:
      - ben
