name: ben
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - scikit-learn
  - pandas
  - tqdm
  - websockets
  - tensorflow-mkl=1.15
  - grpcio-tools
  - bottle
  - gevent
