apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ben
spec:
  selector:
    app: intobridge
    component: ben
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http