name: Upgrade Ben image

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
env:
  AWS_ACCOUNT_ID: "004345335763"
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-push-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: git fetch --prune --unshallow --tags
        continue-on-error: true

      - name: Update the submodule
        run: git submodule update --remote --init --recursive

      - name: Install Build Essential
        run: sudo apt-get install build-essential

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ env.AWS_ACCESS_KEY_ID }}
          password: ${{ env.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ""

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - id: build-and-publish
        name: Build and push ben image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: public.ecr.aws/i8e5j7a1/robot-api:${{ inputs.version }}
          cache-from: type=gha,scope=ben
          cache-to: type=gha,scope=ben,mode=max
