name: Upgrade the DDS API image

on:
  push:
    tags:
       - '*'

env:
  AWS_ACCOUNT_ID: "004345335763"
  AWS_REGION: "eu-central-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-push-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: git fetch --prune --unshallow --tags
        continue-on-error: true

      - name: Update the submodule
        run: git submodule update --remote --init --recursive

      - name: Install Build Essential
        run: sudo apt-get install build-essential

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ env.AWS_ACCESS_KEY_ID }}
          password: ${{ env.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ""

      - name: Build and push the image
        env:
          VERSION: ${{ github.ref_name }}
          DOCKER_REPO: public.ecr.aws/i8e5j7a1/robot-api
          DOCKER_TAG: public.ecr.aws/i8e5j7a1/robot-api:${{ github.ref_name }}
        shell: bash
        run: make buildx_push
